### ISSUE TITLE
Can i parse org/private repo issues??

### ISSUE THREAD

**Issue by fernandopark** [pvdlg/issue-parser#29]
Can i parse org/private repo issues??

**Comment by pvdlg** [comment]
Maybe you can be more specific? What Git host are you using? Is it just a private repo or it hosted on a custom URL? 

I guess if you ask the question it's because you tried and it didn't work. So maybe you can provide an example?

**Comment by fernandopark** [comment]
Im in  Organizations in github and have private repo 
i wanna parse issues for make slackbot. 

for example >

when i input '#{ISSUE_NO} ' 
result -> get ISSUE_DESCRIPTIONS

**Comment by pvdlg** [comment]
So yes, that case is supported.
However It seems you are misunderstanding what this library is doing. It just parse the text of an issue or commit to find issues and pull request references. It doesn't make any API calls to GitHub or other to find additional info such as the description of the referenced issue. You would have to make those API calls yourself.
